<?php

namespace XNova\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ConfigRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfigRepository extends EntityRepository
{
    public function getValueByParameter($parameter) //nom à rallonge++
    {
        $qb = $this->createQueryBuilder('c');
        $qb->where('c.parameter = :parameter')
            ->setParameter('parameter', $parameter);
        
        $query = $qb->getQuery()->getResult();
        if(isset($query[0]))
            return $query[0];
        else
            return null;
    }
    
    public function setValueByParameter($parameter, $value)
    {
        $qb = $this->_em->createQueryBuilder();
        
        $qb->update($this->_entityName, 'c')
            ->set('c.value', $value)
            ->where('c.parameter = :parameter')
                ->setParameter('parameter', $parameter);
        $qb->getQuery()->execute();
        
        
    }
}