<?php

namespace XNova\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TechnologyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TechnologyRepository extends EntityRepository
{
}